### ISSUE TITLE
stan model handling

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#40]
Opening this for observations / discussions on how we include stan models. 

#### stan models included in the session directories, no function includes
We load and print them in the R code included in the quarto sources
- benefits: stan model files are self-contained; `CmdStanModel::print()` prints the functions (with line numbers)
- drawbacks: duplication of function code, no syntax highlighting

#### Single repository of function files
This could be e.g. in `stan/`
- benefits: no duplication of function code
- drawbacks: `CmdStanModel::print()` does not print the function code so people would have to find the files containing the function code to see what the functions do

#### Use the rmarkdown engine
https://mc-stan.org/cmdstanr/articles/r-markdown.html
- benefits: syntax highlighting
- drawbacks: not sure what happens with included functions, no line numbers (though could still print the model of course), doesn't correspond to the normal workflow of loading stan model, printing, sampling

**Comment by seabbs** [comment]
I think one question here is how much people need to know what all the functions do straight from the get go vs if they navigate to them. 

I am currently leaning towards everything in a shared stan code base to reduce code duplication and using functions to extend that. This is due to: 

1. Shorter code files as functions won't be present
2. Easy to write sessions as they get more complex
3. Easier to see connections between sessions (they share functions)
4. We can always load in the functions themselves and print them to show the code (i.e the first time we use them).

**Comment by sbfnk** [comment]
I'm inclined to agree, and this argument gets stronger for the later / more complex sessions.

**Comment by sbfnk** [comment]
Perhaps one way to maximise clarify here is to do as you suggest and have a corresponding R function for every function, as happens to be e.g. in

https://github.com/nfidd/nfidd/blob/2be87cd89467922f8bf08eb88df60aeb73f09816/sessions/05-R-estimation-and-the-renewal-equation/estimate-r.stan#L20
https://github.com/nfidd/nfidd/blob/2be87cd89467922f8bf08eb88df60aeb73f09816/sessions/05-R-estimation-and-the-renewal-equation/index.qmd#L85

**Comment by sbfnk** [comment]
If going with a separate stan directory it raises the question whether we need separate directories for each session (which has some downsides).

**Comment by sbfnk** [comment]
Implemented now as separate stan dir.
